# version: '3.8'
services:
  youtube-downloader:
    build: .
    container_name: youtube-downloader
    ports:
      - "3000:3000"
    volumes:
      - ./public:/app/public
    restart: unless-stopped
